# See https://github.com/actions/runner/issues/1173
name: 'Test GHA "if" expressions (actions/runner#1173)'
on:
  workflow_dispatch:
    inputs:
      empty:
        description: 'Empty string'
        default: ''
      nonempty:
        description: 'Argument'
        default: 'nonempty'
env:
  L: ${{ '${{' }}
  R: '}}'
jobs:
  test:
    name: 'Test GHA "if" expressions (actions/runner#1173)'
    runs-on: ubuntu-latest
    steps:

      # Empty string comparisons
      - name: 'inputs.empty'
        if: inputs.empty
        run: echo
      - name: '${{ env.L }} inputs.empty ${{ env.R }}'
        if: ${{ inputs.empty }}
        run: echo

      - name: 'inputs.empty != '''''
        if: inputs.empty != ''
        run: echo
      - name: '${{ env.L }} inputs.empty != '''' ${{ env.R }}'
        if: ${{ inputs.empty != '' }}
        run: echo

      - name: 'inputs.empty == ''nonempty'''
        if: inputs.empty == 'nonempty'
        run: echo
      - name: '${{ env.L }} inputs.empty == ''nonempty'' ${{ env.R }}'
        if: ${{ inputs.empty == 'nonempty' }}
        run: echo

      - name: 'inputs.empty == '''''
        if: inputs.empty == ''
        run: echo
      - name: '${{ env.L }} inputs.empty == '''' ${{ env.R }}'
        if: ${{ inputs.empty == '' }}
        run: echo

      - name: 'inputs.empty != ''nonempty'''
        if: inputs.empty != 'nonempty'
        run: echo
      - name: '${{ env.L }} inputs.empty != ''nonempty'' ${{ env.R }}'
        if: ${{ inputs.empty != 'nonempty' }}
        run: echo

      # Non-empty string comparisons
      - name: 'inputs.nonempty'
        if: inputs.nonempty
        run: echo
      - name: '${{ env.L }} inputs.nonempty ${{ env.R }}'
        if: ${{ inputs.nonempty }}
        run: echo

      - name: 'inputs.nonempty != '''''
        if: inputs.nonempty != ''
        run: echo
      - name: '${{ env.L }} inputs.nonempty != '''' ${{ env.R }}'
        if: ${{ inputs.nonempty != '' }}
        run: echo

      - name: 'inputs.nonempty == ''nonempty'''
        if: inputs.nonempty == 'nonempty'
        run: echo
      - name: '${{ env.L }} inputs.nonempty == ''nonempty'' ${{ env.R }}'
        if: ${{ inputs.nonempty == 'nonempty' }}
        run: echo

      - name: 'inputs.nonempty == '''''
        if: inputs.nonempty == ''
        run: echo
      - name: '${{ env.L }} inputs.nonempty == '''' ${{ env.R }}'
        if: ${{ inputs.nonempty == '' }}
        run: echo

      - name: 'inputs.nonempty != ''nonempty'''
        if: inputs.nonempty != 'nonempty'
        run: echo
      - name: '${{ env.L }} inputs.nonempty != ''nonempty'' ${{ env.R }}'
        if: ${{ inputs.nonempty != 'nonempty' }}
        run: echo
