name: Test fetch/pull/push
on:
  push:
    branches:
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config pull.rebase false
      - run: git fetch --shallow-exclude=main origin
      - run: git pull origin main
      - run: git push origin main
