name: Build, push rightsize images
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build_rightsize_image:
    runs-on: ubuntu-latest
    steps:
      - name: Env check
        run: |
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}, GITHUB_BASE_REF: ${GITHUB_BASE_REF}, GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          env
      - name: cat release
        run: |
          cat /etc/*-release
      - name: Clone repo (sans submodules)
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_BRANCH }}
      - name: Test concurrent jobs
        run: |
          set -m
          (echo "1: sleeping 8"; sleep 8; echo "1: done sleeping 8") &
          echo "2: sleeping 4"; sleep 4; echo "2: done sleeping 4"
          wait
