name: Build, push rightsize images
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build_rightsize_image:
    runs-on: ubuntu-latest
    steps:
      - name: Env check
        run: |
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}, GITHUB_BASE_REF: ${GITHUB_BASE_REF}, GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          env
