name: Build, push rightsize images
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build_rightsize_image:
    runs-on: ubuntu-latest
    steps:
      - name: Env check
        run: |
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}, GITHUB_BASE_REF: ${GITHUB_BASE_REF}, GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
          env
      - name: Clone repo (sans submodules)
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GIT_BRANCH }}
      - name: Test concurrent jobs
        run: |
          set -m
          (echo "1: sleeping 10"; sleep 10; echo "1: done sleeping 10") >sleep10.txt &
          (echo "2: sleeping 5"; sleep 5; echo "2: done sleeping 5")
          cat sleep10.txt
          fg
